name = "pdf-tools-web"
compatibility_date = "2026-06-24"
pages_build_output_dir = "dist"

[vars]
PDF_TOOLS_DAILY_LIMIT = "10"
PDF_TOOLS_MODEL = "@cf/ibm-granite/granite-4.0-h-micro"
PDF_TOOLS_FALLBACK_MODEL = "@cf/qwen/qwen3-30b-a3b-fp8"

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "PDF_TOOLS_QUOTA"
id = "0643a508af6b490a8e22e7d26cc4da76"
preview_id = "ac32cc4dd8f74878b520d06cfb3cc5f9"
